spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  ai:
    openai:
      temperature: 0.3
      model: gpt-3.5-turbo
      embedding-base-url: https://api.openai.com
      embedding-model: text-embedding-ada-002
